### ISSUE TITLE
Code in this repository is inconsistent with the one in the documentation

### ISSUE THREAD

**Issue by alexislefebvre** [codecov/example-php#1]
According to README.md, the syntax to use with PHP is:

> Add to your `.travis.yml` file.
> ```yml
> after_success:
>   - bash <(curl -s https://codecov.io/bash)
> ```

But the [guide](https://codecov.io/guide) gives a different syntax:

> Append to your `.travis.yml` file
> ```yml
> before_install:
>   - pip install --user codecov
> after_success:
>   - codecov
> ```

What is the recommended code?

**Comment by stevepeak** [comment]
They both do work, sorry for the confusion. I would recommend the Bash for simplicity, but the operate identically. I'll update the docs accordingly, thank you for bringing this to my attention!

Cheers!

**Comment by WebDevJL** [comment]
@stevepeak 

I'm trying to add Codecov to [this repo](https://github.com/Puzzlout/FrameworkMvc) which is setup on [Travis CI](https://travis-ci.org/Puzzlout/FrameworkMvc) and building. 

But I'm not sure what result to expect... Can you troubleshoot my case?

Thanks!

**Comment by stevepeak** [comment]
Hey @WebDevJL looks like the PR above works. Thanks!

**Comment by WebDevJL** [comment]
@stevepeak Excellent!
